stages:
  - test
  - build_and_push
  - deploy

variables:
  IMAGE_NAME: $DOCKER_USERNAME/devops-app:latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

# -----------------------------
# 1. Test
# -----------------------------
test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r app/requirements.txt
    - pytest app/test_app.py -v
  only:
    - main


# -----------------------------
# 2. Build and Push Docker Image
# -----------------------------
build_and_push:
  stage: build_and_push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker info
    - docker build -t $IMAGE_NAME -f docker/Dockerfile .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME
  only:
    - main

# -----------------------------
# 3. Deploy / Update in Kubernetes Cluster
# -----------------------------
deploy:
  stage: deploy
  image: alpine:3.19
  before_script:
    - apk add --no-cache openssh-client bash
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - |
        sed -i "s|image: .*devops-app.*|image: ${IMAGE_NAME}|" kubernetes/deploy.yml
    - scp -o StrictHostKeyChecking=no kubernetes/deploy.yml $EC2_USER@$MASTER_IP:/home/ec2-user/deploy.yml
    - |
      ssh -o StrictHostKeyChecking=no $EC2_USER@$MASTER_IP bash << EOF
        set -e
        export KUBECONFIG=/home/ec2-user/.kube/config
        kubectl apply -f /home/ec2-user/deploy.yml
        kubectl rollout restart deployment/devops-app-deployment
        kubectl rollout status deployment/devops-app-deployment --timeout=300s
      EOF
  only:
    - main